/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tapbo;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import main.TAPBO;
import static main.TAPBO.con;
import static main.TAPBO.pst;
import static main.TAPBO.rs;
import model.Antrian;
import model.AntrianDAO;

/**
 *
 * @author ALOLA
 */
public class FormAntrian extends javax.swing.JInternalFrame {
    
    static FormAntrian instance = null;
    AntrianDAO antriDao;
    /**
     * Creates new form FormAntrian
     */
    public FormAntrian() {
        initComponents();
        daftar();
    }
    
    public static FormAntrian getInstance() {
        if (instance == null) {
            instance = new FormAntrian();
        }
        return instance;
    }
    
    private void empty() {
        fieldPel.setText("");
        fieldNoPol.setText("");
        fieldNoStnk.setText("");
    }
    
    private boolean Validasi() {
        boolean Valid = true;
        String Pesan = "Silahkan Cek Kembali Pengisian Data";

        if (fieldPel.getText().equals("")) {
            Pesan += "\nSilahkan Isi Nama Pelanggan";
            Valid = false;
        }
        if (fieldNoPol.getText().equals("")) {
            Pesan += "\nSilahkan Isi No Polisi Kendaraan";
            Valid = false;
        }
        if (fieldNoStnk.getText().equals("")) {
            Pesan += "\nSilahkan Isi Nomor STNK";
            Valid = false;
        }
        
        return Valid;
    }
    
    public void daftar() {
        String kolom[] = {"Nama Pelanggan", "No Polisi Kendaraan", "No STNK"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        try {
            String sql = "select * from antrian";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                String nama = rs.getString(1);
                String no_polisi = rs.getString(2);
                String no_stnk = rs.getString(3);
                String data[] = {nama, no_polisi, no_stnk};
                dtm.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        antriTabel.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fieldPel = new javax.swing.JTextField();
        insert = new javax.swing.JButton();
        fieldNoPol = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fieldNoStnk = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        close = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        antriTabel = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("MASUKKAN NAMA");

        fieldPel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        insert.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        insert.setText("Tambah Antrian");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });

        fieldNoPol.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("MASUKKAN NO POLISI");

        fieldNoStnk.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("MASUKKAN NO STNK");

        close.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        close.setText("Tutup");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        antriTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Pelanggan", "No Polisi Kendaraan", "No STNK"
            }
        ));
        jScrollPane1.setViewportView(antriTabel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(fieldNoPol, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(fieldNoStnk, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldPel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(insert)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldPel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldNoPol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fieldNoStnk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insert)
                    .addComponent(close))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
if (Validasi()) {
            antriDao = new AntrianDAO();
            Antrian antrian = new Antrian();
            antrian.setNama(fieldPel.getText());
            antrian.setNoPol(fieldNoPol.getText());
            antrian.setNoStnk(fieldNoStnk.getText());

            if (antrian != null) {
                try {
                    antriDao.insert(antrian);
                    daftar();
                    JOptionPane.showMessageDialog(this, "Data telah berhasil disimpan.", "Simpan Data", JOptionPane.INFORMATION_MESSAGE);
                    empty();
                } catch (SQLException ex) {
//                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Antrian Sudah Ada");
                    empty();
                }
            }
        }
    }//GEN-LAST:event_insertActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_closeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable antriTabel;
    private javax.swing.JButton close;
    private javax.swing.JTextField fieldNoPol;
    private javax.swing.JTextField fieldNoStnk;
    private javax.swing.JTextField fieldPel;
    private javax.swing.JButton insert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
